import type { Categoria } from './types'

/**
 * Cardápio completo. Edite preços, nomes, descrições direto aqui — não tem banco.
 * Cada commit + push dispara um deploy automático no Cloudflare Pages.
 *
 * Pra mudar preço:    edite o `preco` do item
 * Pra ocultar item:   apague a linha (ou comente com //)
 * Pra adicionar item: copie uma linha existente, ajuste código/nome/preço
 * Pra destacar item:  adicione `destaque: true` (vira "Pedida da Casa")
 */
export const cardapio: Categoria[] = [
  {
    slug: 'tabuas-1-sabor',
    nome: 'Tábuas (1 sabor)',
    descricao: 'Acompanha fritas',
    itens: [
      { codigo: '41',  nome: 'Carne de Sol c/ Fritas',                preco: 99.99 },
      { codigo: '43',  nome: 'Frango c/ Fritas',                      preco: 79.90 },
      { codigo: '44',  nome: 'Filé c/ Fritas',                        preco: 99.99 },
      { codigo: '54',  nome: '½ Carne de Sol c/ Fritas',              preco: 69.90 },
      { codigo: '55',  nome: 'Camarão Alho e Óleo c/ Fritas',         preco: 109.90 },
      { codigo: '88',  nome: '½ Filé c/ Fritas',                      preco: 69.90 },
      { codigo: '111', nome: '½ Camarão Alho e Óleo c/ Fritas',       preco: 69.90 },
      { codigo: '112', nome: '½ Calabresa c/ Fritas',                 preco: 59.90 },
      { codigo: '113', nome: '½ Frango c/ Fritas',                    preco: 59.90 },
    ],
  },
  {
    slug: 'tabuas-mistinhas',
    nome: 'Tábuas Mistinhas',
    descricao: '2 sabores misturados (porção pequena)',
    itens: [
      { codigo: '110',  nome: 'Camarão e Filé c/ Fritas',           preco: 69.90 },
      { codigo: '1101', nome: 'Camarão e Carne de Sol c/ Fritas',   preco: 69.90 },
      { codigo: '1102', nome: 'Carne de Sol e Filé c/ Fritas',      preco: 69.90 },
      { codigo: '1103', nome: 'Camarão e Frango c/ Fritas',         preco: 69.90 },
      { codigo: '1104', nome: 'Filé de Frango e Filé c/ Fritas',    preco: 69.90 },
      { codigo: '1105', nome: 'Calabresa e Carne de Sol c/ Fritas', preco: 69.90 },
      { codigo: '1106', nome: 'Camarão e Calabresa c/ Fritas',      preco: 69.90 },
      { codigo: '1107', nome: 'Sol e Frango c/ Fritas',             preco: 69.90 },
      { codigo: '1108', nome: 'Filé e Calabresa c/ Fritas',         preco: 69.90 },
      { codigo: '1109', nome: 'Frango e Calabresa c/ Fritas',       preco: 69.90 },
    ],
  },
  {
    slug: 'tabua-mista',
    nome: 'Tábua Mista',
    descricao: '2 sabores combinados (porção média)',
    itens: [
      { codigo: '114',  nome: 'Camarão e Filé c/ Fritas',           preco: 109.99 },
      { codigo: '1141', nome: 'Camarão e Carne de Sol c/ Fritas',   preco: 109.99 },
      { codigo: '1142', nome: 'Camarão e Filé de Frango c/ Fritas', preco: 109.99 },
      { codigo: '1143', nome: 'Camarão e Calabresa c/ Fritas',      preco: 109.99 },
      { codigo: '1144', nome: 'Carne de Sol e Filé c/ Fritas',      preco: 109.99 },
      { codigo: '1145', nome: 'Filé de Frango e Filé c/ Fritas',    preco: 109.99 },
      { codigo: '1146', nome: 'Calabresa e Carne de Sol c/ Fritas', preco: 109.99 },
      { codigo: '1147', nome: 'Sol e Frango c/ Fritas',             preco: 109.99 },
      { codigo: '1148', nome: 'Filé e Calabresa c/ Fritas',         preco: 109.99 },
      { codigo: '1149', nome: 'Frango e Calabresa c/ Fritas',       preco: 109.99 },
    ],
  },
  {
    slug: 'tabua-mistao-2',
    nome: 'Tábua Mistão (2 sabores)',
    descricao: '2 sabores na porção grande',
    itens: [
      { codigo: '104',  nome: 'Camarão e Filé c/ Fritas',           preco: 129.99 },
      { codigo: '1041', nome: 'Camarão e Carne de Sol c/ Fritas',   preco: 129.99 },
      { codigo: '1042', nome: 'Carne de Sol e Filé c/ Fritas',      preco: 129.99 },
      { codigo: '1043', nome: 'Camarão e Frango c/ Fritas',         preco: 129.99 },
      { codigo: '1044', nome: 'Filé de Frango e Filé c/ Fritas',    preco: 129.99 },
      { codigo: '1045', nome: 'Calabresa e Carne de Sol c/ Fritas', preco: 129.99 },
      { codigo: '1046', nome: 'Camarão e Calabresa c/ Fritas',      preco: 129.99 },
      { codigo: '77',   nome: 'Só Camarão c/ Fritas',               preco: 129.99 },
      { codigo: '1047', nome: 'Sol e Frango c/ Fritas',             preco: 129.99 },
      { codigo: '1048', nome: 'Filé e Calabresa c/ Fritas',         preco: 129.99 },
      { codigo: '1049', nome: 'Frango e Calabresa c/ Fritas',       preco: 129.99 },
    ],
  },
  {
    slug: 'tabua-mistao-3',
    nome: 'Tábua Mistão (3 sabores)',
    descricao: '3 sabores combinados',
    itens: [
      { codigo: '115',  nome: 'Calabresa, Carne de Sol e Frango c/ Fritas',     preco: 129.99 },
      { codigo: '1151', nome: 'Filé, Carne de Sol e Filé de Frango c/ Fritas',  preco: 129.99 },
      { codigo: '1152', nome: 'Filé de Frango, Calabresa e Filé c/ Fritas',     preco: 129.99 },
      { codigo: '1153', nome: 'Camarão, Filé e Calabresa c/ Fritas',            preco: 129.99 },
      { codigo: '1154', nome: 'Camarão, Carne de Sol e Filé c/ Fritas',         preco: 129.99 },
      { codigo: '1155', nome: 'Camarão, Carne de Sol e Frango c/ Fritas',       preco: 129.99 },
      { codigo: '1156', nome: 'Camarão, Calabresa e Filé de Frango c/ Fritas',  preco: 129.99 },
      { codigo: '1157', nome: 'Camarão e Calabresa c/ Fritas',                  preco: 129.99 },
      { codigo: '1158', nome: 'Camarão, Frango e Filé c/ Fritas',               preco: 129.99 },
      { codigo: '1159', nome: 'Carne de Sol, Calabresa e Filé',                 preco: 129.99 },
    ],
  },
  {
    slug: 'tabua-mistao-4',
    nome: 'Tábua Mistão (4 sabores)',
    descricao: 'Combinação completa, 4 sabores',
    itens: [
      { codigo: '47',  nome: 'Camarão, Calabresa, Filé Carne, Frango c/ Fritas',                preco: 149.99, destaque: true },
      { codigo: '100', nome: 'Camarão, Filé Carne, Carne de Sol e Filé de Frango c/ Fritas',    preco: 149.99 },
      { codigo: '46',  nome: 'Filé Carne, Carne de Sol, Filé Frango e Calabresa c/ Fritas',     preco: 149.99 },
    ],
  },
  {
    slug: 'petiscos',
    nome: 'Petiscos',
    descricao: 'Pra acompanhar o chopp',
    itens: [
      { codigo: '62',  nome: 'Isca de Frango Empanado',          preco: 37.90 },
      { codigo: '64',  nome: 'Isca de Peixe Empanado',           preco: 39.90 },
      { codigo: '48',  nome: 'Tripa',                            preco: 22.90 },
      { codigo: '49',  nome: 'Batata',                           preco: 25.90 },
      { codigo: '45',  nome: 'Filé Acebolado',                   preco: 49.90 },
      { codigo: '50',  nome: 'Bolinhos de Bacalhau (10 unid.)',  preco: 28.90 },
      { codigo: '51',  nome: 'Bolinhos de Charque (10 unid.)',   preco: 28.90 },
      { codigo: '52',  nome: 'Ovos de Codorna (12 unid.)',       preco: 15.90 },
      { codigo: '53',  nome: 'Queijo Coalho Assado',             preco: 15.90 },
      { codigo: '56',  nome: 'Caldinho de Camarão',              preco: 14.90 },
      { codigo: '156', nome: 'Caldinho de Camarão Pequeno',      preco: 8.90 },
      { codigo: '101', nome: 'Camarão Alho e Óleo',              preco: 55.90 },
      { codigo: '116', nome: '½ Camarão Alho e Óleo',            preco: 29.90 },
      { codigo: '103', nome: 'Amendoim',                         preco: 2.99 },
      { codigo: '42',  nome: 'Carne de Sol Acebolada',           preco: 49.90 },
      { codigo: '70',  nome: 'Frango Acebolado',                 preco: 39.90 },
    ],
  },
  {
    slug: 'hamburguer',
    nome: 'Linha Hambúrguer',
    descricao: 'Os clássicos do Barril',
    itens: [
      { codigo: '65', nome: 'Barril X-burguer',     descricao: 'Pão Bola, Hambúrguer, Queijo e Salada',           preco: 10.99 },
      { codigo: '66', nome: 'Barril X-bacon',       descricao: 'Pão Bola, Hambúrguer, Queijo, Bacon e Salada',    preco: 14.99 },
      { codigo: '67', nome: 'Barril X-burguer Egg', descricao: 'Pão Bola, Hambúrguer, Queijo, Ovo e Salada',      preco: 14.99 },
      { codigo: '68', nome: 'Barril X-calabresa',   descricao: 'Pão Bola, Hambúrguer, Queijo, Calabresa e Salada', preco: 14.99 },
    ],
  },
  {
    slug: 'espetinhos',
    nome: 'Espetinhos',
    descricao: 'Na brasa, no capricho',
    itens: [
      { codigo: '57', nome: 'Espetinho de Frango',           preco: 9.99 },
      { codigo: '58', nome: 'Espetinho de Coração',          preco: 9.99 },
      { codigo: '59', nome: 'Espetinho de Carne',            preco: 13.90 },
      { codigo: '60', nome: 'Espetinho de Camarão',          preco: 13.90 },
      { codigo: '89', nome: 'Espetinho de Frango c/ Bacon',  preco: 13.90 },
    ],
  },
  {
    slug: 'frios',
    nome: 'Frios',
    descricao: 'Tábuas e porções de frios',
    itens: [
      { codigo: '118', nome: 'Frios',                  descricao: 'Queijo, Presunto e Azeitona',         preco: 19.90 },
      { codigo: '61',  nome: 'Tábua de Frios',         descricao: 'Presunto, Queijo, Azeite e Salame',   preco: 39.90 },
      { codigo: '63',  nome: 'Azeitonas',              preco: 11.90 },
      { codigo: '105', nome: 'Porção de Salame',       preco: 24.90 },
      { codigo: '999', nome: 'Embalagem para Viagem',  preco: 1.00 },
    ],
  },
  {
    slug: 'chopp',
    nome: 'Chopp',
    descricao: 'Mar.Beer, caneca e bastão',
    itens: [
      { codigo: '01',  nome: 'Mar.Beer 2.500ml',  descricao: 'Com bastão dentro', preco: 54.90, destaque: true },
      { codigo: '02',  nome: 'Mar.Beer 3.500ml',  descricao: 'Com bastão dentro', preco: 69.90, destaque: true },
      { codigo: '123', nome: 'Chopp 1 Litro',     descricao: 'Com bastão dentro', preco: 26.90 },
      { codigo: '08',  nome: 'Caneca',                                            preco: 12.90 },
      { codigo: '07',  nome: 'Caneca / Vinho',                                    preco: 13.90 },
    ],
  },
  {
    slug: 'long-neck',
    nome: 'Long Neck',
    descricao: 'Cervejas geladíssimas',
    itens: [
      { codigo: '10',  nome: 'Brahma / Itaipava Pilsen / Itaipava 100%',  preco: 7.99 },
      { codigo: '500', nome: 'Heineken Zero',                              preco: 11.00 },
      { codigo: '600', nome: 'Heineken',                                   preco: 13.99 },
      { codigo: '601', nome: 'Stella Artois / Spaten',                     preco: 11.99 },
      { codigo: '602', nome: 'Petra',                                      preco: 9.99 },
      { codigo: '603', nome: 'Budweiser',                                  preco: 11.99 },
      { codigo: '605', nome: 'Corona',                                     preco: 13.99 },
      { codigo: '09',  nome: 'Malzbier',                                   preco: 10.99 },
      { codigo: '12',  nome: 'Cerveja Sem Álcool',                         preco: 9.99 },
    ],
  },
  {
    slug: 'bebidas-sem-alcool',
    nome: 'Bebidas s/ Álcool',
    descricao: 'Águas, refrigerantes, energéticos',
    itens: [
      { codigo: '13',  nome: 'Água Mineral',              preco: 4.99 },
      { codigo: '14',  nome: 'Refrigerante Lata',         preco: 7.99 },
      { codigo: '16',  nome: 'Coca-Cola 500ml',           preco: 9.99 },
      { codigo: '161', nome: 'Refrigerante Litro',        preco: 13.99 },
      { codigo: '17',  nome: 'Coco (copo)',               preco: 6.99 },
      { codigo: '18',  nome: 'Coco (jarra)',              preco: 18.90 },
      { codigo: '133', nome: 'Água Tônica',               preco: 7.99 },
      { codigo: '137', nome: 'Aquarius Fresh / H2O',      preco: 9.99 },
      { codigo: '138', nome: 'TNT Energético',            preco: 9.99 },
      { codigo: '128', nome: 'Red Bull Energético',       preco: 14.99 },
    ],
  },
  {
    slug: 'sucos-taca',
    nome: 'Sucos (taça)',
    descricao: 'Naturais, na taça',
    itens: [
      { codigo: '39',  nome: 'Limão',     preco: 8.99 },
      { codigo: '40',  nome: 'Laranja',   preco: 8.99 },
      { codigo: '401', nome: 'Maracujá',  preco: 8.99 },
      { codigo: '405', nome: 'Cajú',      preco: 8.99 },
      { codigo: '402', nome: 'Acerola',   preco: 8.99 },
      { codigo: '403', nome: 'Cajá',      preco: 8.99 },
      { codigo: '404', nome: 'Graviola',  preco: 8.99 },
      { codigo: '406', nome: 'Goiaba',    preco: 8.99 },
    ],
  },
  {
    slug: 'sucos-jarra',
    nome: 'Sucos (jarra)',
    descricao: 'Naturais, na jarra',
    itens: [
      { codigo: '390', nome: 'Limão',     preco: 24.90 },
      { codigo: '126', nome: 'Laranja',   preco: 24.90 },
      { codigo: '391', nome: 'Maracujá',  preco: 24.90 },
      { codigo: '392', nome: 'Acerola',   preco: 24.90 },
      { codigo: '393', nome: 'Cajá',      preco: 24.90 },
      { codigo: '394', nome: 'Graviola',  preco: 24.90 },
    ],
  },
  {
    slug: 'cachacas',
    nome: 'Cachaças',
    descricao: 'Doses e garrafas',
    itens: [
      { codigo: '32',  nome: 'Serra Limpa / Volúpia',  preco: 6.99 },
      { codigo: '700', nome: 'São Paulo Cristal',       preco: 4.99 },
      { codigo: '80',  nome: 'Triunfo',                 preco: 4.99 },
      { codigo: '108', nome: 'São Paulo',               preco: 4.99 },
      { codigo: '130', nome: 'Rainha / Matuta',         preco: 6.49 },
      { codigo: '132', nome: 'Triunfo Garrafa',        preco: 24.90 },
      { codigo: '701', nome: 'São Paulo Garrafa',      preco: 24.90 },
      { codigo: '703', nome: 'Matuta Garrafa',         preco: 26.90 },
    ],
  },
  {
    slug: 'drinks',
    nome: 'Drinks',
    descricao: 'Caipirinhas, nevadas, doses',
    itens: [
      { codigo: '139', nome: 'Nevada de Morango',                          preco: 19.99 },
      { codigo: '04',  nome: 'Nevada de Kiwi',                             preco: 19.99 },
      { codigo: '131', nome: 'Nevada de Limão',                            preco: 15.90 },
      { codigo: '33',  nome: 'Caipifruta de Morango',                      preco: 19.90 },
      { codigo: '499', nome: 'Caipifruta de Kiwi',                         preco: 19.90 },
      { codigo: '140', nome: 'Caipirinha',                                 preco: 13.90 },
      { codigo: '141', nome: 'Caipiroska Orloff',                          preco: 14.90 },
      { codigo: '20',  nome: 'Martini',                                    preco: 6.99 },
      { codigo: '21',  nome: 'Ron Montilla',                               preco: 6.99 },
      { codigo: '22',  nome: 'Ron Bacardi',                                preco: 7.99 },
      { codigo: '23',  nome: 'Ron Limon / Big Apple',                      preco: 8.99 },
      { codigo: '24',  nome: 'Domecq',                                     preco: 7.99 },
      { codigo: '25',  nome: 'Campari',                                    preco: 9.99 },
      { codigo: '26',  nome: 'Orloff',                                     preco: 8.99 },
      { codigo: '34',  nome: 'Vinho da Casa',                              preco: 10.99 },
      { codigo: '35',  nome: 'Gin',                                        preco: 9.99 },
      { codigo: '78',  nome: 'Vodka Smirnoff',                             preco: 9.99 },
      { codigo: '79',  nome: 'Smirnoff Ice / Ice Cabaré',                  preco: 13.90 },
      { codigo: '134', nome: 'Vinho Quinta do Morgado',                    preco: 29.90 },
      { codigo: '129', nome: 'Dreher',                                     preco: 6.99 },
      { codigo: '135', nome: 'Tequila',                                    preco: 16.90 },
      { codigo: '136', nome: 'Conhaque de Alcatrão',                       preco: 6.99 },
      { codigo: '142', nome: 'Fogo Paulista',                              preco: 8.99 },
      { codigo: '202', nome: 'Amarula',                                    preco: 18.90 },
      { codigo: '203', nome: 'Cointreau / Tanqueray',                      preco: 17.90 },
      { codigo: '207', nome: 'Vinho Garrafa (Reservado / Santa Helena)',   preco: 51.90 },
    ],
  },
  {
    slug: 'whisky',
    nome: 'Whisky',
    descricao: 'Doses selecionadas',
    itens: [
      { codigo: '27',  nome: 'Old Eight',                              preco: 8.99 },
      { codigo: '29',  nome: 'Johnnie Walker Red',                     preco: 14.90 },
      { codigo: '30',  nome: 'White Horse',                            preco: 12.90 },
      { codigo: '99',  nome: 'Old Parr',                               preco: 17.90 },
      { codigo: '124', nome: "Johnnie Walker Black / Jack Daniel's",  preco: 17.90 },
      { codigo: '125', nome: 'Black White',                            preco: 9.99 },
    ],
  },
]
